apiVersion: projectsame.io/v1alpha1
metadata:
    name: TF2RetrainFlowers
pipeline:
    name: "TF2 Retrain Flowers"
    description: "TF2 Retrain Flowers"
    package: "pipeline.py"
run:
    name: "Run 2"
    parameters:
        epochs: 1
        batch_size: 32
        revision: HEAD
debugging_features_flags:
    createStorage: false
