apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=234
  name: model-config
  options:
    disableNameSuffixHash: true
