apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=6487619f080f8de322f655356f04759984b575ba
  name: model-config
  options:
    disableNameSuffixHash: true
