apiVersion: v1
kind: Service
metadata:
  labels:
    app: retrain-ui
  name: retrain-ui
  namespace: kubeflow
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: retrain-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retrain-ui
  name: retrain-ui
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrain-ui
  template:
    metadata:
      labels:
        app: retrain-ui
    spec:
      serviceAccountName: pipeline-runner
      containers:
      - name: app
        image: quay.io/chanwit/retrain-demo-app:v0.1.1
        command: ["/usr/local/bin/streamlit"]
        args: ["run", "app.py"]
        env:
        - name: MODEL_REVISION
          valueFrom:
            configMapKeyRef:
              name: model-config
              key: model-revision
        - name: TAG_NAME
          valueFrom:
            configMapKeyRef:
              name: model-config
              key: tag-name
        - name: MODEL_ENDPOINT_URL
          value: http://f47dc4f41d8ce51e6cfc.southeastasia.cloudapp.azure.com:9000
