apiVersion: v1
data:
  model-revision: d5d2c266ade8282d75c6cee91285b9fe11fd41b0
  tag-name: v0.2.4
kind: ConfigMap
metadata:
  name: model-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: retrain-ui
  name: retrain-ui
  namespace: kubeflow
spec:
  ports:
  - name: http
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: retrain-ui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retrain-ui
  name: retrain-ui
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrain-ui
  template:
    metadata:
      labels:
        app: retrain-ui
    spec:
      containers:
      - args:
        - run
        - app.py
        command:
        - /usr/local/bin/streamlit
        env:
        - name: MODEL_REVISION
          valueFrom:
            configMapKeyRef:
              key: model-revision
              name: model-config
        - name: TAG_NAME
          valueFrom:
            configMapKeyRef:
              key: tag-name
              name: model-config
        - name: MODEL_ENDPOINT_URL
          value: http://f47dc4f41d8ce51e6cfc.southeastasia.cloudapp.azure.com:9000
        image: quay.io/chanwit/retrain-demo-app:v0.1.1
        name: app
      serviceAccountName: pipeline-runner
