apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=cd07ce034c9578a88b6e2244ce0813a6fcca8b49
  - tag-name=v0.3.0
  name: model-config
  options:
    disableNameSuffixHash: true
