apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=8b5e543d9153aff93cfe7c6c73a7beaa9b644e7d
  - tag-name=v0.2.3
  name: model-config
  options:
    disableNameSuffixHash: true
