apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=feefc45d259c4f764dedca9bd1c924f0060dd649
  - tag-name=v0.2.2
  name: model-config
  options:
    disableNameSuffixHash: true
