apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=47170cb5e660825d85afb8a5b19dcf6baced1c8f
  - tag-name=v0.2.1
  name: model-config
  options:
    disableNameSuffixHash: true
