name: run

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: install kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.2"
      - name: Get Metadata
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: update model revision
        run: |
          cd infra/same-ops-prod/app
          rm kustomization.yaml
          # rm generated.yaml || true

          touch kustomization.yaml
          kustomize edit set namespace kubeflow
          kustomize edit add resource deploy.yaml
          kustomize edit add configmap model-config --from-literal=model-revision=${{ github.sha }} --disableNameSuffixHash
          kustomize edit add configmap model-config --from-literal=tag-name=${{ env.TAG }} --disableNameSuffixHash

          # kustomize build . > generated.yaml
          # rm kustomization.yaml
          # touch kustomization.yaml
          # kustomize edit add resource generated.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "promote model built by ${{ env.SHORT_SHA }} to prod"
          base: main
          title: "Promote ${{ env.SHORT_SHA }} to prod"
          body: |
            Promote ${{ env.SHORT_SHA }} to production
            ENV: PROD
            TAG: ${{ env.TAG }}
          branch: promote/model-${{ env.SHORT_SHA }}-to-prod
          delete-branch: true
          labels: |
            automation
